service: serverless-haskell-example

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

functions:
  hello:
    handler: serverless-haskell-example.example-exe

plugins:
  - serverless-haskell
